- hosts: localhost
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:
    - package:
        name:
        - jq
        - gcc
        - python3-devel
        state: present
#      become: yes

    - pip:
        name: pip
        state: latest

    - pip:
        name:
          - ansible[azure]
          - msrest
          - ansible-tower-cli
          - azure-mgmt-managementgroups
          - azure-mgmt-compute
        state: forcereinstall


    - shell: ansible-galaxy collection install azure.azcollection


