- hosts: localhost
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:
    - package:
        name:
        - jq
        - gcc
        - python3-devel
        state: present
#      become: yes

    - pip:
        name: pip
        state: latest

    - pip:
        name:
          - ansible[azure]
          - msrest
          - ansible-tower-cli
          - azure-cli-core
          - azure-cli-nspkg
          - azure-common
          - packaging
          - requests[security]
          - azure-nspkg
          - azure-storage  
          - msrestazure
          - azure-keyvault
          - azure-graphrbac
          - xmltodict
          - azure-mgmt-managementgroups
          - azure-mgmt-compute
          - azure-mgmt-privatedns
          - azure-mgmt-recoveryservicesbackup
          - azure-mgmt-datalake-store
          - azure-mgmt-authorization
          - azure-mgmt-batch
          - azure-mgmt-cdn
          - azure-mgmt-containerinstance
#           - azure-mgmt-containerregistry
          - azure-mgmt-containerservice
          - azure-mgmt-keyvault
          - azure-mgmt-marketplaceordering
          - azure-mgmt-monitor
          - azure-mgmt-managedservices
          - azure-mgmt-network
          - azure-mgmt-nspkg
          - azure-mgmt-redis
          - azure-mgmt-resource
          - azure-mgmt-rdbms
          - azure-mgmt-search
          - azure-mgmt-servicebus
          - azure-mgmt-sql
          - azure-mgmt-storage
          - azure-mgmt-trafficmanager
          - azure-mgmt-web
          - azure-mgmt-cosmosdb
          - azure-mgmt-hdinsight
          - azure-mgmt-devtestlabs
          - azure-mgmt-loganalytics
          - azure-mgmt-automation
          - azure-mgmt-iothub
          - azure-mgmt-recoveryservices
          - azure-mgmt-recoveryservicesbackup
          - azure-mgmt-authorization
          - azure-mgmt-dns
          - azure-mgmt-marketplaceordering 
          - azure-mgmt-managementgroups
          - azure-mgmt-cosmosdb
          - azure-mgmt-hdinsight
          - azure-mgmt-devtestlabs
          - azure-mgmt-loganalytics
          - azure-mgmt-automation
          - azure-mgmt-iothub
          - azure-mgmt-recoveryservices
          - azure-mgmt-recoveryservicesbackup
        state: forcereinstall


    - shell: ansible-galaxy collection install azure.azcollection

      
    - shell: pip3 install azure-cli azure-mgmt-monitor
      register: galaxy_out 
      
    - debug:
        var: galaxy_out
        


