- hosts: localhost
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:
    - package:
        name:
        - jq
        - gcc
        - python3-devel
        state: present
#      become: yes

    - pip:
        name: pip
#         state: latest
#         state: present

    - pip:
        name:
          - ansible[azure]
          - msrest
          - numpy 
#         state: forcereinstall
#         state: latest
#         state: present


    - shell: ansible-galaxy collection install azure.azcollection
        


