- hosts: localhost
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:
    - package:
        name:
        - jq
        - gcc
        - libffi-devel
        - openssl-devel
        - curl
        state: present
      become: yes

    - pip:
        name: pip
        state: latest

    - pip:
        name:
          - ansible[azure]
          - msrest
          - ansible-tower-cli
          - azure-cli
          - azure-nspkg
          - azure-mgmt-nspkg
#          - azure-mgmt-compute

#    - shell: yes | curl -L https://aka.ms/InstallAzureCli | bash


