- hosts: localhost
  collections:
    - awx.awx
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  
    - local_action: copy content={{ item.value }} dest=/tmp/{{ item.name }}.json
      with_items:
        - { name: ssh_keys, value: "{{ ssh_keys }}" }
        - { name: vm, value: "{{ vm }}" }
        - { name: resourcegroup_attribute, value: "{{ resourcegroup_attribute }}" }
        
        

    - shell: jq -s '.[0] * .[1]' /tmp/ssh_keys.json  /tmp/vm.json > /tmp/ssh_keys_vm.json
    - shell: jq -s '.[0] * .[1]' /tmp/resourcegroup_attribute.json  /tmp/ssh_keys_vm.json > /tmp/attributes.json


    - include_vars:
        file: /tmp/attributes.json
        name: attributes

    - set_stats:
        data: "{{ attributes }}"
      register: attributes
