- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    
    - set_fact:
        random_name: "sdia_{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"
        

    - azure_rm_resourcegroup:
        name: "{{random_name}}"
        location: "{{region}}"
        tags:
          creator: sdia
      register: resourcegroup_output
      
      
    - local_action: copy content={{ resourcegroup_output }} dest=/tmp/resourcegroup_output.json
        
 
    - include_tasks: resource_group.yaml
      vars:
        instance_name: "{{ item.key }}"
      loop: "{{ instances | dict2items }}"
      
    - shell: jq '{"{{topology_name}}":{resource_group:.state.name}}' /tmp/resourcegroup_output.json > /tmp/resourcegroup_attribute.json
    
    - include_vars:
        file: /tmp/resourcegroup_attribute.json
        name: resourcegroup_attribute
          
    - set_stats:
        data: "{{resourcegroup_attribute}}"
        
    - set_stats:
        resource_group_name: "{{random_name}}"  
        
        
  
      
      
      
