- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    
    - set_fact:
        random_name: "sdia_{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"
        

    - azure_rm_resourcegroup:
        name: "{{random_name}}"
        location: "{{region}}"
        tags:
          creator: sdia
      register: resourcegroup_output
      
      
    - local_action: copy content={{ resourcegroup_output }} dest=/tmp/resourcegroup_output.json
        
 
    - include_tasks: resource_group.yaml
      vars:
        instance_name: "{{ item.key }}"
      loop: "{{ instances | dict2items }}"
      
    - set_stats:
        data:
          resource_group_name: "{{ random_name }}"
  
      
      
      
