- hosts: localhost
  vars:
  tasks:
    - azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        force_delete_nonempty: yes
        state: absent
      register: resourcegroup_attribute
                      
          
    - set_stats:
        data: 
          "{{topology_name}}": 
            ssh_keys: 
              a: "None"
          "{{topology_name}}": 
            vm: 
              b: "None" 
          "{{topology_name}}": 
            resourcegroup:  
              c: "None"
          "{{topology_name}}": 
            resourcegroup_attribute: "{{resourcegroup_attribute}}"
