- hosts: localhost
  vars:
  tasks:
    - azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        force_delete_nonempty: yes
        state: absent
      register: resourcegroup_attribute
            
    - set_stats:
        data: 
          resourcegroup_attribute: "{{resourcegroup_attribute}}"
