- hosts: localhost
  collections:
    - awx.awx
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:  
  
  
  
    - local_action: copy content={{ item.value }} dest=/tmp/{{ item.name }}.json
      with_items:
        - { name: selected_flavors, value: "{{ selected_flavors }}" }
        - { name: networks, value: "{{ networks }}" }
        - { name: ssh_keys, value: "{{ ssh_keys }}" }
        - { name: resourcegroup, value: "{{ resourcegroup }}" }
        

    - shell: jq -s '.[0] * .[1]' /tmp/images.json /tmp/networks.json > /tmp/images_networks.json

    - shell: jq -s '.[0] * .[1]' /tmp/networks.json /tmp/ssh_keys.json > /tmp/networks_ssh_keys.json

    - shell: jq -s '.[0] * .[1]' /tmp/images_networks_ssh_keys.json  /tmp/selected_flavors.json > /tmp/vms.json
    
  
    - include_vars:
        file: /tmp/vms.json
        name: vms
        
    - include_tasks: vm.yaml
      vars: 
        name: "{{ item.key }}"
        resource_group_name: "{{item.value['attributes']['resource_group_name']}}"
        flavor: "{{item.value['flavor_name']}}"
        user_name: "{{item.value['user_name']}}"
        network_interface_name: "{{item.value['attributes']['resource_group_name']}}"
        os_distro: "{{item.value['os_distro']}}"
        os_version: "{{item.value['os_version']}}"
        publisher_name: "{{item.value['publisher_name']}}"
      loop: "{{ vms | dict2items }}"
