- hosts: localhost
  collections:
    - awx.awx
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:  
  
    - include_vars:
        file: /tmp/vms.json
        name: vms
        
    - include_tasks: vm.yaml
        vars: 
          name: "{{ item.key }}"
          resource_group_name: "{{item.value['attributes']['resource_group_name']}}"
          flavor: "{{item.value['flavor_name']}}"
          user_name: "{{item.value['user_name']}}"
          network_interface_name: "{{item.value['attributes']['network_interface_name']}}"
          os_distro: "{{item.value['os_distro']}}"
          os_version: "{{item.value['os_version']}}"
          publisher_name: "{{item.value['publisher_name']}}"
      loop: "{{ vms | dict2items }}"
