- name: Create and Add items to dictionary
  set_fact: 
      userdata: "{{ userdata | default({}) | combine ({ item.key : item.value }) }}"
    - name: Create and Add items to dictionary
      set_fact: 
          userdata: "{{ userdata | default({}) | combine ({ item.key : item.value }) }}"
      with_items:
        - { 'key': 'Name' , 'value': 'SaravAK'}
        - { 'key': 'Email' , 'value': 'sarav@gritfy.com'}
        - { 'key': 'Location' , 'value': 'Coimbatore'}
        - { 'key': 'Nationality' , 'value': 'Indian'}    - name: Create and Add items to dictionary
      set_fact: 
          userdata: "{{ userdata | default({}) | combine ({ item.key : item.value }) }}"
      with_items:
        - { 'key': 'Name' , 'value': 'SaravAK'}
        - { 'key': 'Email' , 'value': 'sarav@gritfy.com'}
        - { 'key': 'Location' , 'value': 'Coimbatore'}
        - { 'key': 'Nationality' , 'value': 'Indian'}
        
        


- set_fact:
    os_distro:
        key: "{{loop_item.key}}"
        updated_os_distro: UbuntuServer
  loop: "{{ vm_info }}"
  loop_control:
    loop_var: "loop_item"
  when: loop_item.value['os_distro'] == "Ubuntu"
    
- set_fact:
    os_distro:
        key: "{{loop_item.key}}"
        updated_os_distro: "{{loop_item.value['os_distro']}}"
  when: loop_item.value['os_distro'] != "Ubuntu"
  loop: "{{ vm_info }}"
  loop_control:
    loop_var: "loop_item"
    
  
- set_fact:
    os_version:
        key: "{{loop_item.key}}"
        updated_os_version: 18.04-LTS
  loop: "{{ vm_info }}"
  loop_control:
    loop_var: "loop_item"
  when: loop_item.value['os_version'] == "18.04" 
  
  
- set_fact:
    os_version:
        key: "{{loop_item.key}}"
        updated_os_version: "{{loop_item.value['os_version']}}"
  loop: "{{ vm_info }}"
  loop_control:
    loop_var: "loop_item"
  when: loop_item.value['os_version'] != "18.04" 
  
  
- set_fact:
    random_name: "azure_{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"
    
    
- local_action: copy content={{ os_version }} dest=/tmp/{{random_name}}_os_version.json
- local_action: copy content={{ os_distro }} dest=/tmp/{{random_name}}_os_distro.json
- local_action: copy content={{ vm_info }} dest=/tmp/{{random_name}}_vm_info.json


- shell jq . 
- shell: jq -s '.[0] * .[1]' /tmp/{{random_name}}_os_version.json  /tmp/{{random_name}}_os_distro.json > /tmp/{{random_name}}_os_version_os_distro.json  
- shell: jq -s '.[0] * .[1]' /tmp/{{random_name}}_os_version_os_distro.json  /tmp/{{random_name}}_vm_info.json > /tmp/{{random_name}}_updated_vm.json  
        
  
- include_vars:
    file: /tmp/{{random_name}_updated_vm.json
    name: updated_vm
      

- name: Async sleeping for batched_items
  ansible.builtin.command: echo {{ async_item }}
  async: 2400
  poll: 0
  loop: "{{ updated_vm }}"
  loop_control:
    loop_var: "async_item"
  register: async_results

- name: Check sync status
  async_status:
    jid: "{{ async_result_item.ansible_job_id }}"
  loop: "{{ async_results.results }}"
  loop_control:
    loop_var: "async_result_item"
  register: async_poll_results
  until: async_poll_results.finished
  retries: 30
  

# - set_fact:
#     updated_os_distro: UbuntuServer
#   when: os_distro == "Ubuntu"
  
# - set_fact:
#     updated_os_distro: "{{os_distro}}"
#   when: os_distro != "Ubuntu"
  
# - set_fact:
#     updated_os_version: 18.04-LTS
#   when: os_version == "18.04"
  
# - set_fact:
#     updated_os_version: "{{os_version}}"
#   when: os_version != "18.04"
  

# - azure_rm_virtualmachine:
#     resource_group: "{{ resource_group_name }}"
#     name: "{{ vm_name }}"
#     admin_username: "{{ user_name}}"
#     ssh_password_enabled: false
#     image:
#       offer: "{{ updated_os_distro }}"
#       publisher: "{{publisher_name}}"
#       sku: "{{ updated_os_version }}"
#       version: latest
#     ssh_public_keys:
#       - path: /home/{{ user_name}}/.ssh/authorized_keys
#         key_data: "{{public_key}}"
#     vm_size: "{{flavor}}"
#     open_ports:
#       - 22
#       - 80
#       - 443
#       - 8080
#       - 6443
#       - 30000-32767
#   register: vm_output
#   async: 2400
#   poll: 0
#   loop: "{{ vms | dict2items | batch(2) | list}}"
#   loop_control:
#     loop_var: "async_item"

    
# - local_action: copy content={{ vm_output }} dest=/tmp/vm_output.json

# - shell:  jq '.ansible_facts.azure_vm.properties | {"{{ item.key }}":{public_ip:.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress,node_type:.hardwareProfile.vmSize}}' /tmp/vm_output.json
#   register: vm_provision_attributes
  
     
# - set_stats:
#     data:
#       vm: "{{ vm_provision_attributes.stdout }}"
      


# - name: Check sync status
#   async_status:
#     jid: "{{ async_result_item.ansible_job_id }}"
#   loop: "{{ async_results.results }}"
#   loop_control:
#     loop_var: "async_result_item"
#   register: async_poll_results
#   until: async_poll_results.finished
#   retries: 50
  
# - debug:
#     var: async_vm_output
