- hosts: localhost
  collections:
    - awx.awx
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
   - azure_rm_networkinterface:
      resource_group:  "{{ resource_group_name }}"
      name:  "{{ resource_group_name }}"
      virtual_network: "{{ resource_group_name }}"
      subnet: "{{ resource_group_name }}"
      public_ip_name: "{{ resource_group_name }}"
      security_group: "{{ resource_group_name }}"