- hosts: localhost
  collections:
    - awx.awx
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - azure_rm_virtualnetwork:
        resource_group: "{{ resource_group_name }}"
        name: "{{ resource_group_name }}"
        address_prefixes: "172.0.0.0/16"
