- hosts: localhost
  collections:
    - awx.awx
    - azure.azcollection
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    
    - shell: python "{{ playbook_dir }}"/list_vms.py "{{hostvars['localhost']['credentials'][0]['user']}}" "{{hostvars['localhost']['credentials'][0]['token']}}" "{{hostvars['localhost']['credentials'][0]['extra_properties']['subscription_id']}}" "{{hostvars['localhost']['credentials'][0]['extra_properties']['tenant']}}" "{{region}}"
      register: flavors_output
 
    - debug:
        var: flavors_output
