- hosts: localhost
  collections:
    - awx.awx
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: List all available images under current subscription
      azure_rm_image_info:
      register: instance_size_output

    - debug:
        var: instance_size_output
        
    - name: Get facts for one subscription by id
      azure_rm_subscription_info:
        id: "{{hostvars['localhost']['credentials'][0]['extra_properties']['subscription_id']}}"
      register: subscription_info_output

    - debug:
        var: subscription_info_output
        

#     - shell: /var/lib/awx/bin/az vm list-skus
#       register: instance_size_output





#     - debug:
#         var: instance_size_output
