- hosts: localhost
  gather_facts: no
  tasks:


    - include_tasks: get_image.yaml
      vars:
        os_distro: "{{ item.value.os_distro }}"
        os_version: "{{ item.value.os_version }}"
        location: "{{ region }}"
      loop: "{{ hostvars['localhost']['instances'] | dict2items }}"
