- hosts: localhost
  collections:
    - awx.awx
    - azure.azcollection
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - local_action: copy content={{ hostvars['localhost']['instances'] }} dest=/tmp/request_instances.json

    - find:
        paths: /tmp/
        patterns: "flavor_info_output_{{region}}.json"
        age: 30d
      register: older_files
      
    - file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ older_files.files }}"
      
    - stat:
        path: /tmp/flavor_info_output_{{region}}.json
      register: stat_result
      
    - include_vars:
        file: /tmp/flavor_info_output_{{region}}.json
        name: flavor_info_output_cache
      when: stat_result.stat.exists
          
    - shell: python "{{ playbook_dir }}"/list_vms.py "{{hostvars['localhost']['credentials'][0]['user']}}" "{{hostvars['localhost']['credentials'][0]['token']}}" "{{hostvars['localhost']['credentials'][0]['extra_properties']['subscription_id']}}" "{{hostvars['localhost']['credentials'][0]['extra_properties']['tenant']}}" "{{region}}" > /tmp/flavor_info_output_{{region}}.json
      register: flavors_output
      when: not stat_result.stat.exists

    - shell: python "{{ playbook_dir }}"/select_best_flavor.py /tmp/flavor_info_output_{{region}}.json /tmp/request_instances.json
      register: select_best_flavors_output
      

    - include_vars:
        file: "{{ select_best_flavors_output.stdout }}"
        name: selected_flavors

    - set_stats:
        data: "{{selected_flavors}}"
      register: flavor_stats_output

    - debug:
        var: flavor_stats_output
